version: '3'

services:
  mongo_db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

  mongodb-admin:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://admin:secret@mongo_db:27017/
      ME_CONFIG_BASICAUTH: true
    depends_on:
      - mongo_db

  server:
    build: .
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - mongo_db

volumes:
  mongodb-data: